import { useAuth } from "@/_core/hooks/useAuth";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import QueryStateError from "@/components/QueryStateError";
import { arabicNumber, asNumber, observationStatusMeta, periodLabel } from "@/lib/tourism";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, Database, Save } from "lucide-react";
import { useMemo, useState } from "react";
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { toast } from "sonner";

export default function DataEntry() {
  const { user } = useAuth();
  const utils = trpc.useUtils();
  const canWrite = user?.role === "admin" || user?.role === "analyst";
  const indicators = trpc.indicators.list.useQuery();
  const observations = trpc.observations.list.useQuery();
  const [form, setForm] = useState({ indicatorId: "", year: String(new Date().getFullYear()), period: "annual" as "annual" | "quarterly", quarter: "annual", value: "", targetValue: "", source: "", notes: "" });
  const save = trpc.observations.upsert.useMutation({ onSuccess: () => { toast.success("تم حفظ القياس كمسودة للمراجعة."); utils.observations.list.invalidate(); utils.dashboard.summary.invalidate(); setForm({ ...form, value: "", targetValue: "", notes: "" }); }, onError: (error) => toast.error(error.message) });
  const status = trpc.observations.setStatus.useMutation({ onSuccess: () => { toast.success("تم تحديث حالة التحقق."); utils.observations.list.invalidate(); utils.dashboard.summary.invalidate(); }, onError: (error) => toast.error(error.message) });
  const availableIndicators = useMemo(() => (indicators.data ?? []).filter((item) => item.status !== "archived"), [indicators.data]);
  const selectedIndicator = availableIndicators.find((item) => item.id === Number(form.indicatorId));
  const annualSeries = useMemo(() => (observations.data ?? [])
    .filter((item) => item.observation.indicatorId === Number(form.indicatorId) && item.observation.period === "annual")
    .sort((a, b) => a.observation.year - b.observation.year)
    .map((item) => ({ year: item.observation.year, value: asNumber(item.observation.value), target: item.observation.targetValue ? asNumber(item.observation.targetValue) : undefined })), [observations.data, form.indicatorId]);
  function submit(event: React.FormEvent) { event.preventDefault(); if (!canWrite) return; if (!form.indicatorId || !form.value) { toast.error("يرجى اختيار المؤشر وإدخال القيمة."); return; } save.mutate({ indicatorId: Number(form.indicatorId), year: Number(form.year), period: form.period, quarter: form.period === "annual" ? "annual" : form.quarter as "Q1" | "Q2" | "Q3" | "Q4", value: Number(form.value), targetValue: form.targetValue === "" ? null : Number(form.targetValue), source: form.source || undefined, notes: form.notes || undefined }); }
  return <div className="space-y-6"><section><h1 className="page-title">إدخال البيانات الدورية</h1><p className="page-subtitle">إدخال قياسات سنوية وربع سنوية، وربطها بالمصدر وحالة التحقق للمراجعة والاعتماد.</p></section>
    {(indicators.isError || observations.isError) && <QueryStateError message="تعذر تحميل المؤشرات أو سجل القياسات." onRetry={() => { indicators.refetch(); observations.refetch(); }} />}
    {canWrite ? <form onSubmit={submit} className="section-card p-5 md:p-6"><div className="mb-5 flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#e6f1ee] text-[#0f5c58]"><Database className="h-5 w-5" /></span><div><h2 className="font-bold text-[#173f3d]">إضافة أو تحديث قياس</h2><p className="mt-1 text-xs text-slate-500">يتحول الإدخال إلى مسودة؛ استخدم الحالة أدناه لمراجعته أو اعتماده.</p></div></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Field label="المؤشر"><Select value={form.indicatorId} onValueChange={(value) => setForm({ ...form, indicatorId: value })}><SelectTrigger><SelectValue placeholder="اختر مؤشراً" /></SelectTrigger><SelectContent>{availableIndicators.map((item) => <SelectItem key={item.id} value={String(item.id)}>{item.name} — {item.code}</SelectItem>)}</SelectContent></Select></Field><Field label="السنة"><Input type="number" min="2000" max="2100" value={form.year} onChange={(e) => setForm({ ...form, year: e.target.value })} /></Field><Field label="نوع الفترة"><Select value={form.period} onValueChange={(value: "annual" | "quarterly") => setForm({ ...form, period: value, quarter: value === "annual" ? "annual" : "Q1" })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="annual">سنوي</SelectItem><SelectItem value="quarterly">ربع سنوي</SelectItem></SelectContent></Select></Field><Field label="الربع"><Select value={form.quarter} onValueChange={(value) => setForm({ ...form, quarter: value })} disabled={form.period === "annual"}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{["Q1", "Q2", "Q3", "Q4"].map((q) => <SelectItem key={q} value={q}>{q}</SelectItem>)}</SelectContent></Select></Field><Field label="القيمة"><Input required inputMode="decimal" type="number" step="any" value={form.value} onChange={(e) => setForm({ ...form, value: e.target.value })} /></Field><Field label="القيمة المستهدفة"><Input inputMode="decimal" type="number" step="any" value={form.targetValue} onChange={(e) => setForm({ ...form, targetValue: e.target.value })} /></Field><Field label="مصدر البيانات"><Input value={form.source} onChange={(e) => setForm({ ...form, source: e.target.value })} placeholder="اسم الجهة أو النظام المصدر" /></Field><Field label="ملاحظات"><Textarea value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} placeholder="توضيح مختصر عند الحاجة" /></Field></div><Button type="submit" className="mt-5 bg-[#0f5c58] hover:bg-[#0a4845]" disabled={save.isPending}><Save className="ml-1.5 h-4 w-4" />حفظ القياس</Button></form> : <div className="rounded-2xl border border-[#cfe0da] bg-[#edf7f3] px-5 py-4 text-sm leading-7 text-[#23574e]">دور viewer يتيح عرض البيانات المعتمدة وسجل القياسات فقط، ولا يتيح إدخال بيانات جديدة.</div>}
    {form.indicatorId && <section className="section-card p-5 md:p-6"><div className="mb-4"><h2 className="font-bold text-[#173f3d]">مقارنة متعددة السنوات</h2><p className="mt-1 text-xs text-slate-500">الاتجاه السنوي للمؤشر المحدد: {selectedIndicator?.name ?? "—"}.</p></div>{annualSeries.length ? <div className="h-64" dir="ltr"><ResponsiveContainer width="100%" height="100%"><LineChart data={annualSeries} margin={{ top: 8, right: 16, left: -18, bottom: 0 }}><CartesianGrid strokeDasharray="3 3" stroke="#e4ece9" /><XAxis dataKey="year" tick={{ fill: "#64748b", fontSize: 12 }} /><YAxis tick={{ fill: "#64748b", fontSize: 12 }} /><Tooltip formatter={(value) => arabicNumber.format(Number(value))} /><Line type="monotone" dataKey="value" name="القيمة" stroke="#0f5c58" strokeWidth={3} dot={{ r: 4 }} />{annualSeries.some((point) => point.target !== undefined) && <Line type="monotone" dataKey="target" name="المستهدف" stroke="#c58a3f" strokeDasharray="6 4" strokeWidth={2} dot={false} />}</LineChart></ResponsiveContainer></div> : <div className="rounded-xl border border-dashed border-[#cfe0da] bg-[#f8fbf9] p-5 text-sm leading-7 text-slate-500">لا توجد قياسات سنوية للمؤشر المحدد بعد؛ ستظهر المقارنة فور حفظ أول قياس سنوي.</div>}</section>}
    <section className="table-shell"><div className="border-b border-[#e8efec] p-4"><h2 className="font-bold text-[#173f3d]">سجل القياسات</h2><p className="mt-1 text-xs text-slate-500">يشمل القياسات السنوية والربع سنوية وحالة تحقق كل قياس.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-right text-sm"><thead className="bg-[#f6f9f7] text-xs text-slate-500"><tr><th className="px-5 py-3">المؤشر</th><th className="px-4 py-3">الفترة</th><th className="px-4 py-3">القيمة</th><th className="px-4 py-3">المصدر</th><th className="px-4 py-3">حالة التحقق</th>{canWrite && <th className="px-4 py-3">إجراء</th>}</tr></thead><tbody className="divide-y divide-[#edf2ef]">{observations.isLoading ? <tr><td colSpan={6} className="p-8 text-center text-slate-500">جارٍ تحميل القياسات…</td></tr> : observations.data?.length ? observations.data.map((item) => <tr key={item.observation.id} className="hover:bg-[#fbfdfc]"><td className="px-5 py-3.5"><p className="font-semibold text-[#244844]">{item.indicator.name}</p><p className="mt-0.5 text-xs text-slate-500" dir="ltr">{item.indicator.code}</p></td><td className="px-4 py-3.5 text-slate-600">{arabicNumber.format(item.observation.year)} · {periodLabel(item.observation.period, item.observation.quarter)}</td><td className="px-4 py-3.5 font-bold text-[#0f5c58]">{arabicNumber.format(asNumber(item.observation.value))} <span className="text-xs font-normal text-slate-500">{item.indicator.unit}</span></td><td className="px-4 py-3.5 text-slate-600">{item.observation.source || "—"}</td><td className="px-4 py-3.5"><Badge className={`${observationStatusMeta[item.observation.verificationStatus].className} border-0`}>{observationStatusMeta[item.observation.verificationStatus].label}</Badge></td>{canWrite && <td className="px-4 py-3.5"><Select value={item.observation.verificationStatus} onValueChange={(value: "draft" | "reviewed" | "approved" | "rejected") => status.mutate({ id: item.observation.id, status: value })}><SelectTrigger className="h-8 w-32"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="draft">مسودة</SelectItem><SelectItem value="reviewed">قيد المراجعة</SelectItem><SelectItem value="approved">معتمد</SelectItem><SelectItem value="rejected">مرفوض</SelectItem></SelectContent></Select></td>}</tr>) : <tr><td colSpan={6} className="p-10 text-center text-slate-500">لا توجد قياسات مسجلة حتى الآن.</td></tr>}</tbody></table></div></section>
  </div>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label><span className="field-label">{label}</span>{children}</label>; }
