import React, { useMemo, useState } from "react";
import { Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Archive, BadgeCheck, CalendarRange, Database, Download, FileText, ShieldAlert } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import QueryStateError from "@/components/QueryStateError";

const numberFormat = new Intl.NumberFormat("ar-LY", { maximumFractionDigits: 2 });

export default function HistoricalArchive() {
  const archive = trpc.historical.overview.useQuery();
  const [selectedCode, setSelectedCode] = useState<string>("");
  const data = archive.data;
  const selected = useMemo(() => data?.indicators.find((indicator) => indicator.code === selectedCode) ?? data?.indicators[0], [data?.indicators, selectedCode]);
  const series = useMemo(() => data?.observations.filter((row) => row.indicatorId === selected?.id).map((row) => ({ ...row, label: String(row.year) })) ?? [], [data?.observations, selected?.id]);

  if (archive.isError) return <QueryStateError message="تعذر تحميل الأرشيف التاريخي. يرجى إعادة المحاولة بعد التحقق من الاتصال." onRetry={() => { void archive.refetch(); }} />;
  if (archive.isLoading || !data) return <div className="grid min-h-[28rem] place-items-center text-sm text-slate-500">يجري تجهيز الأرشيف التاريخي…</div>;

  const cards = [
    { label: "امتداد الأرشيف", value: data.summary.firstYear ? `${data.summary.firstYear} – ${data.summary.lastYear}` : "—", icon: CalendarRange, tone: "bg-amber-50 text-amber-700" },
    { label: "سنوات موثقة", value: numberFormat.format(data.summary.documentedYears), icon: CalendarRange, tone: "bg-indigo-50 text-indigo-700" },
    { label: "قياسات تاريخية", value: numberFormat.format(data.summary.observations), icon: Database, tone: "bg-teal-50 text-teal-700" },
    { label: "مؤشرات موحدة", value: numberFormat.format(data.summary.indicators), icon: Archive, tone: "bg-sky-50 text-sky-700" },
    { label: "قياسات معتمدة", value: numberFormat.format(data.summary.approved), icon: BadgeCheck, tone: "bg-emerald-50 text-emerald-700" },
  ];

  return <div className="space-y-6">
    <section className="relative overflow-hidden rounded-[1.5rem] bg-gradient-to-l from-[#0b5551] to-[#12726b] px-6 py-7 text-white shadow-[0_18px_50px_rgba(14,90,85,.18)] md:px-8">
      <div className="pointer-events-none absolute -left-10 -top-12 h-44 w-44 rounded-full border-[24px] border-[#d6a24e]/20" />
      <div className="relative max-w-3xl"><p className="text-xs font-bold tracking-[.14em] text-amber-200">ذاكرة البيانات السياحية الوطنية</p><h1 className="mt-2 text-2xl font-bold md:text-3xl">الأرشيف التاريخي للمؤشرات</h1><p className="mt-3 max-w-2xl text-sm leading-7 text-teal-50/90">سلسلة موثقة ومعتمدة من التقارير الأصلية الصادرة عن مركز المعلومات والتوثيق السياحي. تُعرض الفجوات كما هي ولا تُستبدل بقيم صفرية، بينما تبقى المواد الجزئية منفصلة عن القياسات السنوية.</p><div className="mt-5 flex flex-wrap gap-2"><a href="/manus-storage/historical_observatory_import_package_0b2b1338.xlsx" download className="inline-flex h-10 items-center gap-2 rounded-xl bg-white/95 px-4 text-sm font-bold text-[#0d5b56] transition hover:bg-white"><Download className="h-4 w-4" />تنزيل حزمة الأرشيف للمراجعة</a><a href={data.officialPublisher.verificationUrl} target="_blank" rel="noreferrer" className="inline-flex h-10 items-center rounded-xl border border-white/30 bg-white/10 px-4 text-sm font-bold text-white transition hover:bg-white/20">المصدر الرسمي: {data.officialPublisher.name}</a></div></div>
    </section>

    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{cards.map((card) => <article key={card.label} className="rounded-2xl border border-[#dce8e4] bg-white p-4 shadow-sm"><div className={`mb-3 grid h-10 w-10 place-items-center rounded-xl ${card.tone}`}><card.icon className="h-5 w-5" /></div><p className="text-xs text-slate-500">{card.label}</p><p className="mt-1 text-xl font-bold text-[#173f3c]">{card.value}</p></article>)}</section>

    <section className="grid gap-5 xl:grid-cols-[1.6fr_1fr]">
      <article className="rounded-2xl border border-[#dce8e4] bg-white p-5 shadow-sm"><div className="mb-4 flex flex-wrap items-end justify-between gap-3"><div><h2 className="font-bold text-[#173f3c]">مسار المؤشر عبر الزمن</h2><p className="mt-1 text-xs text-slate-500">لا تظهر السنوات التي لا تحمل قياساً في المصدر كقيم صفرية.</p></div><label className="w-full sm:w-64"><span className="field-label">المؤشر التاريخي</span><Select value={selected?.code ?? ""} onValueChange={setSelectedCode}><SelectTrigger className="w-full"><SelectValue placeholder="اختر مؤشراً" /></SelectTrigger><SelectContent>{data.indicators.map((indicator) => <SelectItem key={indicator.id} value={indicator.code}>{indicator.name}</SelectItem>)}</SelectContent></Select></label></div>{selected && series.length ? <><div className="mb-3 flex items-center justify-between rounded-xl bg-[#f4f8f6] px-3 py-2 text-xs"><span className="font-semibold text-[#173f3c]">{selected.name}</span><span className="text-slate-500">الوحدة: {selected.unit}</span></div><div className="h-72"><ResponsiveContainer width="100%" height="100%"><LineChart data={series} margin={{ top: 8, right: 12, left: 4, bottom: 4 }}><CartesianGrid strokeDasharray="3 3" stroke="#e3ece9" /><XAxis dataKey="label" tick={{ fontSize: 11 }} /><YAxis tick={{ fontSize: 11 }} width={56} tickFormatter={(value) => numberFormat.format(value)} /><Tooltip formatter={(value: number) => numberFormat.format(value)} labelFormatter={(label) => `السنة ${label}`} /><Line type="monotone" dataKey="value" name="القيمة" stroke="#0f766e" strokeWidth={3} dot={{ r: 3 }} activeDot={{ r: 5 }} isAnimationActive={false} /></LineChart></ResponsiveContainer></div></> : <div className="grid h-72 place-items-center rounded-xl border border-dashed border-[#dce8e4] text-sm text-slate-500">لا توجد قياسات سنوية لهذا المؤشر ضمن الأرشيف الحالي.</div>}</article>
      <article className="rounded-2xl border border-[#dce8e4] bg-white p-5 shadow-sm"><h2 className="font-bold text-[#173f3c]">تغطية السنوات</h2><p className="mt-1 text-xs text-slate-500">عدد القياسات المستخرجة في كل سنة.</p><div className="mt-5 h-72">{data.coverage.length ? <ResponsiveContainer width="100%" height="100%"><BarChart data={data.coverage} margin={{ top: 6, right: 6, left: -15, bottom: 0 }}><CartesianGrid strokeDasharray="3 3" stroke="#e3ece9" /><XAxis dataKey="year" tick={{ fontSize: 10 }} /><YAxis tick={{ fontSize: 10 }} allowDecimals={false} /><Tooltip labelFormatter={(label) => `السنة ${label}`} /><Bar dataKey="observations" name="القياسات" fill="#c58a3f" radius={[5, 5, 0, 0]} isAnimationActive={false} /></BarChart></ResponsiveContainer> : <div className="grid h-full place-items-center text-sm text-slate-500">لا توجد تغطية بعد.</div>}</div></article>
    </section>

    <section className="grid gap-5 lg:grid-cols-[1.25fr_.75fr]"><article className="rounded-2xl border border-[#dce8e4] bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><FileText className="h-5 w-5 text-[#0f766e]" /><div><h2 className="font-bold text-[#173f3c]">سجل المصادر الأرشيفية</h2><p className="text-xs text-slate-500">يفصل السجل بين القياسات المستوردة والمواد التفصيلية أو الجزئية التي تحتاج معالجة إضافية.</p></div></div><div className="mt-4 max-h-64 space-y-2 overflow-auto pl-1">{data.sourceRegistry.map((source) => <div key={source.fileName} className="rounded-xl border border-[#e3ece9] bg-[#fbfdfc] px-3 py-2"><div className="flex items-center justify-between gap-2"><span className="text-xs font-semibold text-[#173f3c]">{source.fileName}</span><span className="shrink-0 rounded-full bg-[#e7f2ee] px-2 py-0.5 text-[10px] font-bold text-[#0f766e]">{source.coverage}</span></div><p className="mt-1 text-[11px] leading-5 text-slate-500"><strong>{source.status}: </strong>{source.detail}</p></div>)}</div></article><article className="rounded-2xl border border-emerald-200 bg-emerald-50/60 p-5 shadow-sm"><div className="flex items-center gap-2 text-emerald-800"><BadgeCheck className="h-5 w-5" /><h2 className="font-bold">حالة الجودة والاعتماد</h2></div><p className="mt-3 text-sm leading-7 text-emerald-900/80">تم اعتماد {numberFormat.format(data.summary.approved)} قياساً بعد إسنادها إلى {data.officialPublisher.name} عبر صفحة الإصدارات الرسمية. تغطي القياسات {numberFormat.format(data.summary.documentedYears)} سنة موثقة ضمن امتداد زمني قدره {numberFormat.format(data.summary.spanYears)} سنة، مع {numberFormat.format(data.summary.gapYears)} فجوات ظاهرة.</p><p className="mt-3 flex items-center gap-2 text-xs font-semibold text-amber-700"><ShieldAlert className="h-4 w-4" /> قياسات بانتظار استكمال التحقق: {numberFormat.format(data.summary.reviewed)}</p></article></section>
  </div>;
}
