import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, Globe2, Layers3, MapPinned, ShieldCheck, Sparkles } from "lucide-react";
import { Link } from "wouter";

const numberFormat = new Intl.NumberFormat("ar-LY");
const destinationVisuals = { visit_libya: { icon: Globe2, tone: "from-[#0f766e] to-[#1e9a8e]", label: "قصص وبيانات وجهات الزوار" }, libya_atlas: { icon: MapPinned, tone: "from-[#176579] to-[#36a2b5]", label: "طبقات مكانية وقراءة جغرافية" } } as const;

export default function PublicationShowcase() {
  const { data, isLoading, isError } = trpc.publication.showcase.useQuery();
  if (isLoading) return <div className="grid gap-5 md:grid-cols-2"><Skeleton className="h-72 rounded-3xl" /><Skeleton className="h-72 rounded-3xl" /></div>;
  if (isError || !data) return <Card className="border-rose-200 bg-rose-50"><CardContent className="p-6 text-rose-800">تعذر تحميل واجهات البيانات في الوقت الحالي.</CardContent></Card>;
  return <div className="space-y-6"><section className="relative overflow-hidden rounded-[2rem] bg-[#123e52] px-6 py-10 text-white shadow-[0_20px_55px_rgba(17,63,83,.18)] md:px-10"><div className="absolute -left-16 -top-16 h-56 w-56 rounded-full border-[30px] border-sky-200/15" /><div className="relative max-w-3xl"><span className="inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/10 px-3 py-1 text-xs font-bold text-sky-100"><Sparkles className="h-3.5 w-3.5 text-amber-200" />من مصدر البيانات الوطني الموحد</span><h1 className="mt-4 text-3xl font-bold md:text-4xl">واجهات السياحة الرقمية</h1><p className="mt-4 text-sm leading-8 text-sky-50/90">استكشف كيف تُجهّز القياسات المعتمدة للمدن السياحية لعرضها داخل Visit Libya وأطلس ليبيا. هذه واجهة عرض محلية للمستخدمين ولا تنقل بيانات إلى أي جهة خارجية.</p></div></section><section className="grid gap-4 sm:grid-cols-3"><ShowcaseMetric icon={Layers3} label="قياسات مدنية معتمدة" value={numberFormat.format(data.summary.spatialApproved)} /><ShowcaseMetric icon={MapPinned} label="مدن ومواقع مفهرسة" value={numberFormat.format(data.summary.activeSpatialAreas)} /><ShowcaseMetric icon={ShieldCheck} label="قاعدة العرض" value="معتمد فقط" /></section><section className="grid gap-5 md:grid-cols-2">{data.destinations.map((destination) => { const visual = destinationVisuals[destination.code]; const Icon = visual.icon; return <article key={destination.code} className="overflow-hidden rounded-3xl border border-[#dce8e4] bg-white shadow-sm"><div className={`bg-gradient-to-l ${visual.tone} p-6 text-white`}><Icon className="h-8 w-8 text-white/90" /><h2 className="mt-8 text-2xl font-bold">{destination.name}</h2><p className="mt-2 text-sm text-white/85">{visual.label}</p></div><div className="p-6"><Badge className="border-0 bg-[#eaf4f1] text-[#0f766e]">عرض محلي منظم</Badge><p className="mt-4 min-h-14 text-sm leading-7 text-slate-600">{destination.description ?? "واجهة بيانات موحدة للقياسات السياحية المعتمدة."}</p><div className="mt-5 flex items-center justify-between border-t border-[#edf2f0] pt-4"><span className="text-xs text-slate-500">يشمل السنوات والمؤشرات والمصدر وحالة التحقق.</span><Link href="/spatial"><Button size="sm" variant="outline" className="border-[#b8d6ce] text-[#0f5c58]">استكشاف المدن <ArrowLeft className="mr-1.5 h-3.5 w-3.5" /></Button></Link></div></div></article>; })}</section></div>;
}

function ShowcaseMetric({ icon: Icon, label, value }: { icon: typeof Layers3; label: string; value: string }) { return <Card className="border-[#dce8e4] shadow-sm"><CardContent className="flex items-center gap-3 p-4"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#eaf4f1] text-[#0f766e]"><Icon className="h-5 w-5" /></span><div><p className="text-xs text-slate-500">{label}</p><p className="mt-1 font-bold text-[#173f3c]">{value}</p></div></CardContent></Card>; }
