import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { exportDashboardPdf } from "@/lib/dashboardPdf";
import { downloadPublicationWorkbook } from "@/lib/publicationShowcaseExport";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, ChartNoAxesCombined, FileSpreadsheet, FileText, Globe2, Layers3, MapPinned, ShieldCheck, Sparkles } from "lucide-react";
import { useMemo, useRef, useState } from "react";
import { Bar, BarChart, CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { toast } from "sonner";
import { Link } from "wouter";

const numberFormat = new Intl.NumberFormat("ar-LY");
const destinationVisuals = { visit_libya: { icon: Globe2, tone: "from-[#0f766e] to-[#1e9a8e]", label: "قصص وبيانات وجهات الزوار" }, libya_atlas: { icon: MapPinned, tone: "from-[#176579] to-[#36a2b5]", label: "طبقات مكانية وقراءة جغرافية" } } as const;

export default function PublicationShowcase() {
  const { data, isLoading, isError } = trpc.publication.showcase.useQuery();
  const showcaseRef = useRef<HTMLDivElement>(null);
  const [selectedIndicatorCode, setSelectedIndicatorCode] = useState("");
  const series = useMemo(() => {
    if (!data) return null;
    return data.analytics.indicatorSeries.find((item) => item.code === selectedIndicatorCode) ?? data.analytics.indicatorSeries[0] ?? null;
  }, [data, selectedIndicatorCode]);

  if (isLoading) return <div className="grid gap-5 md:grid-cols-2"><Skeleton className="h-72 rounded-3xl" /><Skeleton className="h-72 rounded-3xl" /></div>;
  if (isError || !data) return <Card className="border-rose-200 bg-rose-50"><CardContent className="p-6 text-rose-800">تعذر تحميل واجهات البيانات في الوقت الحالي.</CardContent></Card>;

  const exportExcel = async () => {
    try { await downloadPublicationWorkbook(data); toast.success("تم تجهيز ملف Excel من القياسات المعتمدة فقط."); }
    catch { toast.error("تعذر إنشاء ملف Excel في الوقت الحالي."); }
  };
  const exportPdf = async () => {
    if (!showcaseRef.current) return;
    try { await exportDashboardPdf(showcaseRef.current, `واجهات-السياحة-الرقمية-${new Date().toISOString().slice(0, 10)}.pdf`); toast.success("تم تجهيز ملف PDF للواجهة الحالية."); }
    catch { toast.error("تعذر إنشاء ملف PDF في الوقت الحالي."); }
  };

  return <div ref={showcaseRef} className="space-y-6">
    <section className="relative overflow-hidden rounded-[2rem] bg-[#123e52] px-6 py-10 text-white shadow-[0_20px_55px_rgba(17,63,83,.18)] md:px-10"><div className="absolute -left-16 -top-16 h-56 w-56 rounded-full border-[30px] border-sky-200/15" /><div className="relative flex flex-col gap-6 xl:flex-row xl:items-end xl:justify-between"><div className="max-w-3xl"><span className="inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/10 px-3 py-1 text-xs font-bold text-sky-100"><Sparkles className="h-3.5 w-3.5 text-amber-200" />من مصدر البيانات الوطني الموحد</span><h1 className="mt-4 text-3xl font-bold md:text-4xl">واجهات السياحة الرقمية</h1><p className="mt-4 text-sm leading-8 text-sky-50/90">استكشف القياسات المعتمدة للمدن السياحية كما ستُعرض داخل Visit Libya وأطلس ليبيا. هذه واجهة محلية للمستخدمين ولا تنقل بيانات إلى أي جهة خارجية.</p></div><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={exportExcel} className="border-white/40 bg-white/10 text-white hover:bg-white/20 hover:text-white"><FileSpreadsheet className="ml-1.5 h-4 w-4" />Excel</Button><Button size="sm" onClick={exportPdf} className="bg-white text-[#174c5f] hover:bg-sky-50"><FileText className="ml-1.5 h-4 w-4" />PDF</Button></div></div></section>
    <section className="grid gap-4 sm:grid-cols-3"><ShowcaseMetric icon={Layers3} label="قياسات مدنية معتمدة" value={numberFormat.format(data.summary.spatialApproved)} /><ShowcaseMetric icon={MapPinned} label="مدن ومواقع مفهرسة" value={numberFormat.format(data.summary.activeSpatialAreas)} /><ShowcaseMetric icon={ShieldCheck} label="قاعدة العرض" value="معتمد فقط" /></section>
    <section className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><Card className="border-[#dce8e4] shadow-sm"><CardContent className="p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex items-center gap-2"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#eaf4f1] text-[#0f766e]"><ChartNoAxesCombined className="h-5 w-5" /></span><div><h2 className="font-bold text-[#173f3c]">سلسلة المؤشر المدني المعتمد</h2><p className="mt-1 text-xs leading-6 text-slate-500">يُرسم مؤشر واحد ووحدة واحدة في كل مرة؛ لا يتم خلط الوحدات أو إدراج مسودات.</p></div></div></div>{data.analytics.indicatorSeries.length > 0 && <select aria-label="اختيار مؤشر الرسم" value={series?.code ?? ""} onChange={(event) => setSelectedIndicatorCode(event.target.value)} className="h-9 min-w-52 rounded-lg border border-[#cfe0da] bg-white px-3 text-sm text-[#173f3c] outline-none ring-offset-2 focus:ring-2 focus:ring-[#0f766e]">{data.analytics.indicatorSeries.map((item) => <option key={item.code} value={item.code}>{item.name} — {item.unit}</option>)}</select>}</div>{series ? <div className="mt-5 h-[300px]" dir="ltr"><ResponsiveContainer width="100%" height="100%"><LineChart data={series.points} margin={{ top: 10, right: 18, left: 4, bottom: 8 }}><CartesianGrid strokeDasharray="3 3" stroke="#dce8e4" /><XAxis dataKey="year" tick={{ fill: "#5c6f6b", fontSize: 12 }} /><YAxis tick={{ fill: "#5c6f6b", fontSize: 12 }} /><Tooltip formatter={(value: number) => [numberFormat.format(value), `إجمالي ${series.unit}`]} labelFormatter={(year) => `السنة ${year}`} /><Legend /><Line type="monotone" dataKey="value" name={`إجمالي ${series.unit}`} stroke="#0f766e" strokeWidth={3} dot={{ r: 4, fill: "#d49a3f" }} activeDot={{ r: 6 }} /></LineChart></ResponsiveContainer></div> : <EmptyChart text="لا توجد قياسات مدنية معتمدة كافية لرسم سلسلة مؤشر حتى الآن." />}</CardContent></Card>
      <Card className="border-[#dce8e4] shadow-sm"><CardContent className="p-5"><div className="flex items-center gap-2"><span className="grid h-9 w-9 place-items-center rounded-xl bg-sky-50 text-sky-700"><MapPinned className="h-5 w-5" /></span><div><h2 className="font-bold text-[#173f3c]">تغطية المدن عبر السنوات</h2><p className="mt-1 text-xs leading-6 text-slate-500">عدد السجلات والمدن التي تحوي قياسات سنوية معتمدة.</p></div></div>{data.analytics.coverageByYear.length ? <div className="mt-5 h-[300px]" dir="ltr"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.analytics.coverageByYear} margin={{ top: 10, right: 8, left: -8, bottom: 8 }}><CartesianGrid strokeDasharray="3 3" stroke="#dce8e4" /><XAxis dataKey="year" tick={{ fill: "#5c6f6b", fontSize: 12 }} /><YAxis tick={{ fill: "#5c6f6b", fontSize: 12 }} /><Tooltip formatter={(value: number) => [numberFormat.format(value), "عدد"]} labelFormatter={(year) => `السنة ${year}`} /><Legend /><Bar dataKey="records" name="قياسات معتمدة" fill="#176579" radius={[6, 6, 0, 0]} /><Bar dataKey="cities" name="مدن مغطاة" fill="#d49a3f" radius={[6, 6, 0, 0]} /></BarChart></ResponsiveContainer></div> : <EmptyChart text="لا تتوفر تغطية مدنية سنوية معتمدة للرسم." />}</CardContent></Card></section>
    <section className="grid gap-4 md:grid-cols-2">{data.analytics.gaps.map((gap) => <Card key={gap.code} className={`border shadow-sm ${gap.records ? "border-emerald-200 bg-emerald-50/40" : "border-amber-200 bg-amber-50/50"}`}><CardContent className="flex items-start justify-between gap-4 p-5"><div><p className="font-bold text-[#173f3c]">{gap.label}</p><p className="mt-2 text-xs leading-6 text-slate-600">{gap.records ? "تتوفر قياسات مدنية معتمدة وتظهر في ملف التصدير." : "لا توجد قيمة سنوية مدنية معتمدة في المصدر الحالي؛ تُحفظ الفجوة كما هي دون وضع أصفار بديلة."}</p></div><Badge className={`shrink-0 border-0 ${gap.records ? "bg-emerald-100 text-emerald-800" : "bg-amber-100 text-amber-900"}`}>{gap.records ? `${numberFormat.format(gap.records)} قياس` : "مصدر مطلوب"}</Badge></CardContent></Card>)}</section>
    <section className="grid gap-5 md:grid-cols-2">{data.destinations.map((destination) => { const visual = destinationVisuals[destination.code]; const Icon = visual.icon; return <article key={destination.code} className="overflow-hidden rounded-3xl border border-[#dce8e4] bg-white shadow-sm"><div className={`bg-gradient-to-l ${visual.tone} p-6 text-white`}><Icon className="h-8 w-8 text-white/90" /><h2 className="mt-8 text-2xl font-bold">{destination.name}</h2><p className="mt-2 text-sm text-white/85">{visual.label}</p></div><div className="p-6"><Badge className="border-0 bg-[#eaf4f1] text-[#0f766e]">عرض محلي منظم</Badge><p className="mt-4 min-h-14 text-sm leading-7 text-slate-600">{destination.description ?? "واجهة بيانات موحدة للقياسات السياحية المعتمدة."}</p><div className="mt-5 flex items-center justify-between border-t border-[#edf2f0] pt-4"><span className="text-xs text-slate-500">يشمل السنوات والمؤشرات والمصدر وحالة التحقق.</span><Link href="/spatial"><Button size="sm" variant="outline" className="border-[#b8d6ce] text-[#0f5c58]">استكشاف المدن <ArrowLeft className="mr-1.5 h-3.5 w-3.5" /></Button></Link></div></div></article>; })}</section>
  </div>;
}

function ShowcaseMetric({ icon: Icon, label, value }: { icon: typeof Layers3; label: string; value: string }) { return <Card className="border-[#dce8e4] shadow-sm"><CardContent className="flex items-center gap-3 p-4"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#eaf4f1] text-[#0f766e]"><Icon className="h-5 w-5" /></span><div><p className="text-xs text-slate-500">{label}</p><p className="mt-1 font-bold text-[#173f3c]">{value}</p></div></CardContent></Card>; }
function EmptyChart({ text }: { text: string }) { return <div className="mt-5 grid h-[300px] place-items-center rounded-2xl border border-dashed border-[#cfe0da] bg-[#f8fbfa] px-5 text-center text-sm leading-7 text-slate-600">{text}</div>; }
