import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { trpc } from "@/lib/trpc";
import { ArrowRight, Building2, Database, ExternalLink, FileCheck2, Landmark, MapPinned, WalletCards } from "lucide-react";
import { Link, useRoute } from "wouter";

const numberFormat = new Intl.NumberFormat("ar-LY");

export default function SpatialDetail() {
  const [, params] = useRoute("/spatial/:areaId");
  const areaId = Number(params?.areaId);
  const { data, isLoading, isError } = trpc.spatial.detail.useQuery({ areaId }, { enabled: Number.isInteger(areaId) && areaId > 0 });

  if (isLoading) return <div className="grid gap-4"><Skeleton className="h-40 rounded-3xl" /><Skeleton className="h-72 rounded-2xl" /></div>;
  if (isError || !data) return <Card className="border-rose-200 bg-rose-50"><CardContent className="space-y-4 p-7 text-rose-800"><p className="font-bold">تعذر العثور على صفحة الموقع المطلوبة.</p><Link href="/spatial"><Button variant="outline" className="border-rose-300 text-rose-800"><ArrowRight className="ml-2 h-4 w-4" />العودة إلى الخريطة</Button></Link></CardContent></Card>;

  const { area, observations, summary, children } = data;
  const siteObservations = observations.filter((row) => row.indicatorCode === "SPATIAL-TOURISM-SITES-COUNT");
  const investmentObservations = observations.filter((row) => row.indicatorCode === "SPATIAL-TOURISM-INVESTMENT-LYD");
  return <div className="space-y-6">
    <section className="relative overflow-hidden rounded-[2rem] bg-[#0d5b56] px-6 py-8 text-white shadow-[0_20px_55px_rgba(11,84,79,.18)] md:px-9"><div className="absolute -left-12 -top-12 h-44 w-44 rounded-full border-[24px] border-amber-300/15" /><div className="relative"><Link href="/spatial" className="inline-flex items-center gap-2 text-xs font-bold text-amber-100 transition hover:text-white"><ArrowRight className="h-4 w-4" />العودة إلى الخريطة التفاعلية</Link><p className="mt-6 text-xs font-bold tracking-[.14em] text-amber-200">تفاصيل المدينة</p><h1 className="mt-2 text-3xl font-bold">{area.name}</h1><p className="mt-3 text-sm text-teal-50/90">مدينة سياحية · رمز المدينة: {area.code}</p></div></section>

    <section className="grid gap-4 md:grid-cols-3"><Metric icon={Database} label="قياسات معتمدة" value={numberFormat.format(summary.approvedObservations)} /><Metric icon={FileCheck2} label="أحدث قياس" value={summary.latestValue === null ? "لا توجد بيانات" : `${numberFormat.format(summary.latestValue)} ${summary.latestUnit ?? ""}`} /><Metric icon={MapPinned} label="آخر سنة" value={summary.latestYear ? String(summary.latestYear) : "—"} /></section>

    <section className="rounded-2xl border border-[#dce8e4] bg-white p-5 shadow-sm"><div><p className="text-xs font-bold tracking-[.12em] text-[#b98238]">محاور تنموية مخصصة</p><h2 className="mt-1 font-bold text-[#153c39]">المواقع السياحية والاستثمار السنوي</h2><p className="mt-1 text-xs leading-6 text-slate-500">تعرض القيم المعتمدة فقط. عند عدم توافرها، يبقى مصدر البيانات مطلوباً ولا تستبدل القيمة بصفر.</p></div><div className="mt-4 grid gap-4 md:grid-cols-2"><ThematicMetric icon={Landmark} title="المواقع السياحية الموثقة" unit="موقع" rows={siteObservations} empty="لا توجد قيمة سنوية معتمدة للمواقع بعد." /><ThematicMetric icon={WalletCards} title="قيمة الاستثمار السياحي" unit="د.ل" rows={investmentObservations} empty="لا توجد قيمة سنوية معتمدة للاستثمار بعد." /></div></section>

    <section className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><article className="rounded-2xl border border-[#dce8e4] bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="font-bold text-[#153c39]">مرجع الحدود الإدارية</h2><p className="mt-1 text-xs text-slate-500">تظهر المراجع الرسمية فقط؛ لا تُعرض هندسة حدودية غير موثقة.</p></div><Badge variant="outline" className="border-[#b8d6ce] text-[#0f766e]">{area.boundaryStatus === "verified" ? "موثق" : area.boundaryStatus === "submitted" ? "قيد التحقق" : "غير مرفق"}</Badge></div><div className="mt-4 rounded-xl bg-[#f7fbf9] p-4 text-sm leading-7 text-slate-700"><p><strong>المصدر الجغرافي:</strong> {area.geographicSource ?? "لم يحدد بعد"}</p><p className="mt-2"><strong>المرجع:</strong> {area.boundaryReferenceTitle ?? "لم يرفق بعد"}</p>{area.boundaryReferenceUrl ? <a href={area.boundaryReferenceUrl} target="_blank" rel="noreferrer" className="mt-3 inline-flex items-center gap-1.5 font-semibold text-[#0f766e] hover:underline">فتح المرجع الرسمي <ExternalLink className="h-4 w-4" /></a> : null}</div></article><article className="rounded-2xl border border-[#dce8e4] bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-amber-50 text-[#b98238]"><Building2 className="h-5 w-5" /></span><div><h2 className="font-bold text-[#153c39]">النطاق المكاني المرتبط</h2><p className="mt-1 text-xs text-slate-500">مدن أو وحدات مرتبطة بالموقع المرجعي.</p></div></div>{children.length ? <div className="mt-4 flex flex-wrap gap-2">{children.map((child) => <Link key={child.id} href={`/spatial/${child.id}`} className="rounded-full bg-[#eaf4f1] px-3 py-1.5 text-xs font-bold text-[#0f766e] transition hover:bg-[#d7ebe4]">{child.name}</Link>)}</div> : <p className="mt-5 rounded-xl border border-dashed border-[#cfe1db] p-3 text-xs leading-6 text-slate-500">لا توجد وحدات مكانية فرعية مرتبطة بهذا الموقع.</p>}</article></section>

    <section className="overflow-hidden rounded-2xl border border-[#dce8e4] bg-white shadow-sm"><div className="flex flex-col gap-1 border-b border-[#e5eeeb] px-5 py-4 md:flex-row md:items-center md:justify-between"><div><h2 className="font-bold text-[#153c39]">القياسات المكانية المعتمدة</h2><p className="mt-1 text-xs text-slate-500">تشمل القياسات السنوية المعتمدة المرتبطة بالموقع فقط.</p></div><Badge variant="outline" className="w-fit border-[#b8d6ce] text-[#0f766e]">{numberFormat.format(observations.length)} سجل</Badge></div>{observations.length === 0 ? <div className="p-10 text-center"><MapPinned className="mx-auto h-9 w-9 text-[#91b7ad]" /><p className="mt-3 font-semibold text-[#173f3c]">لا توجد قياسات مكانية معتمدة لهذا الموقع بعد</p><p className="mx-auto mt-2 max-w-xl text-sm leading-7 text-slate-500">تظهر القياسات هنا بعد إسنادها إلى الموقع من مصدر رسمي ومرورها بمسار المراجعة والاعتماد.</p></div> : <div className="overflow-auto"><table className="w-full min-w-[760px] text-right text-sm"><thead className="bg-[#f6faf8] text-xs text-slate-500"><tr><th className="px-5 py-3">الموقع</th><th className="px-5 py-3">المؤشر</th><th className="px-5 py-3">السنة</th><th className="px-5 py-3">القيمة</th><th className="px-5 py-3">المصدر</th></tr></thead><tbody>{observations.map((row) => <tr key={row.id} className="border-t border-[#edf2f0]"><td className="px-5 py-3 font-semibold text-[#173f3c]">{row.areaName}</td><td className="px-5 py-3 text-slate-600">{row.indicatorName}</td><td className="px-5 py-3 text-slate-600">{row.year}</td><td className="px-5 py-3 font-bold text-[#0f766e]">{numberFormat.format(row.value)} {row.unit}</td><td className="max-w-72 truncate px-5 py-3 text-xs text-slate-500">{row.source ?? "—"}</td></tr>)}</tbody></table></div>}</section>
  </div>;
}

function Metric({ icon: Icon, label, value }: { icon: typeof Database; label: string; value: string }) { return <Card className="border-[#dce8e4] shadow-sm"><CardContent className="flex items-center gap-3 p-4"><span className="grid h-10 w-10 place-items-center rounded-xl bg-teal-50 text-[#0f766e]"><Icon className="h-5 w-5" /></span><div><p className="text-xs text-slate-500">{label}</p><p className="mt-1 font-bold text-[#173f3c]">{value}</p></div></CardContent></Card>; }

function ThematicMetric({ icon: Icon, title, unit, rows, empty }: { icon: typeof Landmark; title: string; unit: string; rows: { year: number; value: number; source: string | null }[]; empty: string }) {
  const latest = rows[0];
  return <article className="rounded-xl border border-[#dce8e4] bg-[#f8fbfa] p-4"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-amber-50 text-[#b98238]"><Icon className="h-5 w-5" /></span><div><h3 className="font-bold text-[#173f3c]">{title}</h3><p className="mt-1 text-xs text-slate-500">سلسلة سنوية موثقة للمدينة</p></div></div>{latest ? <div className="mt-4"><p className="text-2xl font-bold text-[#0f766e]">{numberFormat.format(latest.value)} <span className="text-sm font-semibold">{unit}</span></p><p className="mt-1 text-xs text-slate-500">سنة {latest.year} · {latest.source ?? "مصدر موثق"}</p><div className="mt-3 flex flex-wrap gap-1.5">{rows.slice(0, 4).map((row) => <span key={`${row.year}-${row.value}`} className="rounded-full border border-[#cfe1db] bg-white px-2 py-1 text-[11px] text-[#315b55]">{row.year}: {numberFormat.format(row.value)}</span>)}</div></div> : <p className="mt-4 rounded-lg border border-dashed border-[#cfe1db] bg-white px-3 py-3 text-xs leading-6 text-slate-500">{empty} اطلب من قسم الإحصاء سنة مدنية كاملة وقيمة ووحدة ومصدر ورقم جدول أو صفحة.</p>}</article>;
}
