import { MapView } from "@/components/Map";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import { trpc } from "@/lib/trpc";
import { buildSpatialColorScale } from "@shared/spatialColorScale";
import { buildLocationQuickStats, type LocationQuickStat } from "@shared/spatialQuickStats";
import { exportSpatialPdf, exportSpatialPng } from "@/lib/spatialExport";
import { Building2, Database, FileDown, ImageDown, MapPinned, Map as MapIcon, RefreshCw, Search, ShieldCheck, Trophy } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";
import { toast } from "sonner";
import { useLocation } from "wouter";

const numberFormat = new Intl.NumberFormat("ar-LY");
const all = "all";

export default function SpatialExplorer() {
  const [selectedYear, setSelectedYear] = useState(all);
  const [selectedIndicator, setSelectedIndicator] = useState(all);
  const [locationQuery, setLocationQuery] = useState("");
  const [comparePrimary, setComparePrimary] = useState(all);
  const [compareSecondary, setCompareSecondary] = useState(all);
  const [map, setMap] = useState<google.maps.Map | null>(null);
  const [mapFailure, setMapFailure] = useState(false);
  const [mapLoading, setMapLoading] = useState(true);
  const [mapRetryKey, setMapRetryKey] = useState(0);
  const [isExporting, setIsExporting] = useState<"png" | "pdf" | null>(null);
  const markerRefs = useRef<google.maps.Marker[]>([]);
  const spatialExportRef = useRef<HTMLDivElement>(null);
  const [, setLocation] = useLocation();

  const filters = useMemo(() => ({ year: selectedYear === all ? undefined : Number(selectedYear), indicatorId: selectedIndicator === all ? undefined : Number(selectedIndicator) }), [selectedIndicator, selectedYear]);
  const { data, isLoading, isError, refetch } = trpc.spatial.overview.useQuery(filters);
  const { data: colorData } = trpc.spatial.overview.useQuery({ indicatorId: selectedIndicator === all ? undefined : Number(selectedIndicator) });
  const { data: rankings } = trpc.spatial.cityRankings.useQuery();
  const cities = data?.cities ?? [];
  const filteredCities = useMemo(() => cities.filter((city) => `${city.name} ${city.code}`.toLocaleLowerCase("ar").includes(locationQuery.trim().toLocaleLowerCase("ar"))), [cities, locationQuery]);
  const locationQuickStats = useMemo(() => buildLocationQuickStats(cities, cities, data?.observations ?? []), [cities, data?.observations]);
  const colorScale = useMemo(() => buildSpatialColorScale(colorData?.observations ?? [], selectedIndicator !== all), [colorData?.observations, selectedIndicator]);
  const primaryRow = data?.observations.find((row) => String(row.areaId) === comparePrimary);
  const secondaryRow = data?.observations.find((row) => String(row.areaId) === compareSecondary);
  const comparisonDifference = primaryRow && secondaryRow && primaryRow.unit === secondaryRow.unit ? primaryRow.value - secondaryRow.value : null;

  const handleExport = async (format: "png" | "pdf") => {
    if (!spatialExportRef.current) return;
    try {
      setIsExporting(format);
      const fileName = `city-tourism-summary-${new Date().toISOString().slice(0, 10)}.${format}`;
      if (format === "png") await exportSpatialPng(spatialExportRef.current, fileName);
      else await exportSpatialPdf(spatialExportRef.current, fileName);
      toast.success(format === "png" ? "تم تنزيل صورة ملخص المدن." : "تم تنزيل ملف PDF لملخص المدن.");
    } catch { toast.error("تعذر تصدير ملخص المدن. حاول مجدداً."); }
    finally { setIsExporting(null); }
  };

  useEffect(() => {
    if (!map || !data || !window.google) return;
    markerRefs.current.forEach((marker) => marker.setMap(null));
    markerRefs.current = [];
    if (filteredCities.length === 0) return;
    const geocoder = new window.google.maps.Geocoder();
    const bounds = new window.google.maps.LatLngBounds();
    let cancelled = false;
    filteredCities.forEach((city) => {
      geocoder.geocode({ address: `${city.name}، ليبيا` }, (results, status) => {
        if (cancelled || status !== "OK" || !results?.[0]?.geometry?.location) return;
        const stat = locationQuickStats.get(city.id) ?? emptyQuickStat();
        const marker = new window.google.maps.Marker({ map, position: results[0].geometry.location, title: city.name, label: { text: city.name.slice(0, 1), color: "#ffffff", fontWeight: "700" }, icon: { path: window.google.maps.SymbolPath.CIRCLE, scale: 11, fillColor: colorScale.colorFor(city.id), fillOpacity: 1, strokeColor: "#ffffff", strokeWeight: 2 } });
        const info = new window.google.maps.InfoWindow({ content: mapQuickStatHtml(city.name, stat) });
        marker.addListener("mouseover", () => info.open({ map, anchor: marker }));
        marker.addListener("mouseout", () => info.close());
        marker.addListener("click", () => setLocation(`/spatial/${city.id}`));
        markerRefs.current.push(marker);
        bounds.extend(results[0].geometry.location);
        if (markerRefs.current.length === filteredCities.length) map.fitBounds(bounds, 80);
      });
    });
    return () => { cancelled = true; markerRefs.current.forEach((marker) => marker.setMap(null)); };
  }, [colorScale, data, filteredCities, locationQuickStats, map, setLocation]);

  return <div className="space-y-6">
    <section className="relative overflow-hidden rounded-[2rem] bg-[#0d5b56] px-6 py-8 text-white shadow-[0_20px_55px_rgba(11,84,79,.18)] md:px-9"><div className="absolute -left-14 -top-14 h-52 w-52 rounded-full border-[28px] border-amber-300/15" /><div className="relative flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div className="max-w-3xl"><p className="text-xs font-bold tracking-[.14em] text-amber-200">طبقة المدن السياحية</p><h1 className="mt-2 text-2xl font-bold md:text-3xl">المدن الأكثر قيمة في السياحة</h1><p className="mt-3 max-w-2xl text-sm leading-7 text-teal-50/90">عرض مدني مباشر للقياسات السياحية المعتمدة. تظهر كل فئة في ترتيب مستقل حتى لا تُجمع وحدات قياس مختلفة في قيمة واحدة.</p></div><div className="flex items-center gap-2 rounded-2xl border border-white/20 bg-white/10 px-4 py-3 text-xs text-teal-50"><ShieldCheck className="h-5 w-5 text-amber-200" /><span>الترتيب: أحدث قياس معتمد لكل مدينة وفئة</span></div></div></section>

    <section className="rounded-2xl border border-[#dce8e4] bg-white p-4 shadow-sm md:p-5"><div className="grid gap-4 xl:grid-cols-[1.4fr_.8fr_.9fr_auto]"><div><p className="mb-2 text-xs font-bold text-slate-600">بحث عن مدينة</p><div className="relative"><Search className="absolute right-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[#0f766e]" /><Input className="pr-9" value={locationQuery} onChange={(event) => setLocationQuery(event.target.value)} placeholder="ابحث باسم المدينة أو رمزها" /></div></div><div><p className="mb-2 text-xs font-bold text-slate-600">السنة</p><Select value={selectedYear} onValueChange={setSelectedYear}><SelectTrigger><SelectValue placeholder="كل السنوات" /></SelectTrigger><SelectContent><SelectItem value={all}>كل السنوات</SelectItem>{(data?.availableYears ?? []).map((year) => <SelectItem key={year} value={String(year)}>{year}</SelectItem>)}</SelectContent></Select></div><div><p className="mb-2 text-xs font-bold text-slate-600">المؤشر</p><Select value={selectedIndicator} onValueChange={setSelectedIndicator}><SelectTrigger><SelectValue placeholder="كل المؤشرات" /></SelectTrigger><SelectContent><SelectItem value={all}>كل المؤشرات المنشورة</SelectItem>{(data?.indicators ?? []).map((indicator) => <SelectItem key={indicator.id} value={String(indicator.id)}>{indicator.name}</SelectItem>)}</SelectContent></Select></div><Button variant="outline" className="h-10 self-end border-[#cfe0dc] text-[#0d5b56]" onClick={() => { setSelectedYear(all); setSelectedIndicator(all); setLocationQuery(""); }}>إعادة الضبط</Button></div><div className="mt-3 flex items-center gap-2 rounded-xl border border-[#e1ece8] bg-[#f8fbfa] p-3 text-xs text-slate-600"><Search className="h-4 w-4 text-[#0f766e]" /><span>نتائج المدن: <strong className="text-[#173f3c]">{filteredCities.length}</strong></span></div></section>

    {isLoading ? <section className="grid gap-4 md:grid-cols-3">{Array.from({ length: 3 }).map((_, index) => <Skeleton key={index} className="h-28 rounded-2xl" />)}</section> : isError ? <Card className="border-rose-200 bg-rose-50"><CardContent className="flex items-center justify-between gap-3 p-6 text-sm text-rose-700"><span>تعذر تحميل بيانات المدن حالياً.</span><Button variant="outline" className="border-rose-300 text-rose-700" onClick={() => refetch()}><RefreshCw className="ml-2 h-4 w-4" />إعادة المحاولة</Button></CardContent></Card> : <>
      <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={Building2} label="المدن في العرض" value={numberFormat.format(filteredCities.length)} tone="amber" /><Metric icon={Database} label="قياسات مدنية معتمدة" value={numberFormat.format(data?.summary.approvedObservations ?? 0)} tone="blue" /><Metric icon={MapIcon} label="أحدث سنة متاحة" value={data?.summary.latestYear ? String(data.summary.latestYear) : "—"} tone="teal" /><Metric icon={MapPinned} label="الترتيبات المتاحة" value={numberFormat.format((rankings ?? []).filter((item) => item.indicator).length)} tone="slate" /></section>

      <section className="grid gap-5 xl:grid-cols-[1.35fr_.65fr]"><article className="overflow-hidden rounded-2xl border border-[#dce8e4] bg-white shadow-sm"><div className="flex items-center justify-between border-b border-[#e5eeeb] px-5 py-4"><div><h2 className="font-bold text-[#153c39]">خريطة المدن التفاعلية</h2><p className="mt-1 text-xs text-slate-500">انقر على المدينة لفتح تفاصيلها، ويتغير اللون وفق أحدث قياس معتمد للمؤشر المختار.</p></div><Badge className={`border-0 ${mapLoading ? "bg-amber-50 text-amber-700" : "bg-[#e7f2ee] text-[#0f766e]"}`}>{mapLoading ? "جاري التحميل" : `${filteredCities.length} مدن`}</Badge></div>{mapFailure ? <CityMapFallback cities={filteredCities} colorFor={colorScale.colorFor} onSelect={(id) => setLocation(`/spatial/${id}`)} onRetry={() => { setMapLoading(true); setMapFailure(false); setMapRetryKey((key) => key + 1); }} /> : <MapView className="h-[430px]" initialCenter={{ lat: 26.3351, lng: 17.2283 }} initialZoom={5} onMapReady={setMap} onMapError={() => setMapFailure(true)} onMapLoadingChange={setMapLoading} retryKey={mapRetryKey} />}</article><CityDirectory cities={filteredCities} onSelect={(id) => setLocation(`/spatial/${id}`)} /></section>

      <CityColorLegend scale={colorScale} selectedIndicator={selectedIndicator !== all} />
      <CityRankingBoard rankings={rankings ?? []} onSelect={(id) => setLocation(`/spatial/${id}`)} />
      <CityHoverGuide cities={filteredCities} summaries={locationQuickStats} onSelect={(id) => setLocation(`/spatial/${id}`)} />
      <div ref={spatialExportRef}><CityExportSummary cities={filteredCities} rankings={rankings ?? []} scale={colorScale} selectedYear={selectedYear} selectedIndicator={selectedIndicator} onExport={handleExport} isExporting={isExporting} /></div>

      <section className="grid gap-5 xl:grid-cols-[.9fr_1.1fr]"><CityComparison cities={data?.cities ?? []} primary={comparePrimary} secondary={compareSecondary} onPrimary={setComparePrimary} onSecondary={setCompareSecondary} selectedYear={selectedYear} selectedIndicator={selectedIndicator} primaryRow={primaryRow} secondaryRow={secondaryRow} difference={comparisonDifference} /><CityObservationsTable observations={data?.observations ?? []} /></section>
    </>}
  </div>;
}

function Metric({ icon: Icon, label, value, tone }: { icon: typeof MapIcon; label: string; value: string; tone: "teal" | "amber" | "blue" | "slate" }) { const tones = { teal: "bg-teal-50 text-[#0f766e]", amber: "bg-amber-50 text-[#b26d1e]", blue: "bg-sky-50 text-sky-700", slate: "bg-slate-100 text-slate-600" }; return <Card className="border-[#dce8e4] shadow-sm"><CardContent className="flex items-center gap-3 p-4"><span className={`grid h-10 w-10 place-items-center rounded-xl ${tones[tone]}`}><Icon className="h-5 w-5" /></span><div><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold text-[#173f3c]">{value}</p></div></CardContent></Card>; }
function CityDirectory({ cities, onSelect }: { cities: { id: number; name: string; code: string }[]; onSelect: (id: number) => void }) { return <aside className="rounded-2xl border border-[#dce8e4] bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="font-bold text-[#153c39]">دليل المدن</h2><p className="mt-1 text-xs text-slate-500">اختر مدينة لصفحة التفاصيل.</p></div><MapPinned className="h-5 w-5 text-[#b98238]" /></div><div className="mt-4 space-y-2">{cities.map((city) => <button key={city.id} onClick={() => onSelect(city.id)} className="flex w-full items-center justify-between rounded-xl border border-[#e3ece9] bg-[#fbfdfc] px-3 py-2.5 text-right transition hover:border-[#91c8ba] hover:bg-[#f2faf7]"><span className="font-semibold text-[#173f3c]">{city.name}</span><span className="text-[10px] text-slate-500">{city.code}</span></button>)}</div><div className="mt-4 rounded-xl border border-dashed border-amber-300 bg-amber-50 p-3 text-xs leading-6 text-amber-900">يظهر هذا العرض المدن السياحية فقط، وتُرتب قيمها حسب كل فئة مستقلة عندما تتوفر قياسات معتمدة.</div></aside>; }
function CityMapFallback({ cities, colorFor, onSelect, onRetry }: { cities: { id: number; name: string }[]; colorFor: (id: number) => string; onSelect: (id: number) => void; onRetry: () => void }) { const positions: Record<string, string> = { "طرابلس": "right-[16%] top-[23%]", "بنغازي": "right-[47%] top-[28%]", "سبها": "right-[36%] top-[66%]" }; return <div className="relative h-[430px] overflow-hidden bg-[radial-gradient(circle_at_80%_20%,rgba(79,180,172,.25),transparent_24%),linear-gradient(145deg,#f0f7f4,#deece7)]"><span className="absolute left-[7%] top-[8%] rounded-full border border-[#c4ddd5] bg-white/70 px-3 py-1.5 text-xs font-bold text-[#0f766e]">عرض المدن البديل</span><Button size="sm" variant="outline" className="absolute right-5 top-5 z-10 border-[#b9d7cf] bg-white/90 text-[#0f766e]" onClick={onRetry}><RefreshCw className="ml-1.5 h-3.5 w-3.5" />إعادة تحميل الخريطة</Button>{cities.map((city) => <button key={city.id} onClick={() => onSelect(city.id)} className={`absolute ${positions[city.name] ?? "right-1/2 top-1/2"} group -translate-x-1/2 -translate-y-1/2 text-center`}><span style={{ backgroundColor: colorFor(city.id) }} className="mx-auto grid h-11 w-11 place-items-center rounded-full border-4 border-white text-sm font-bold text-white shadow-lg transition group-hover:scale-110">{city.name.slice(0, 1)}</span><span className="mt-2 block rounded-lg bg-white/90 px-2 py-1 text-xs font-bold text-[#173f3c] shadow-sm">{city.name}</span></button>)}</div>; }
function CityColorLegend({ scale, selectedIndicator }: { scale: ReturnType<typeof buildSpatialColorScale>; selectedIndicator: boolean }) { return <section className="rounded-2xl border border-[#dce8e4] bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><h2 className="font-bold text-[#153c39]">مقياس لون المدن</h2><p className="mt-1 text-xs text-slate-500">يستخدم أحدث قيمة سنوية معتمدة للمؤشر المختار فقط.</p></div><Badge variant="outline" className="w-fit border-[#b8d6ce] text-[#0f766e]">{selectedIndicator && scale.min !== null ? `${numberFormat.format(scale.min)} – ${numberFormat.format(scale.max ?? 0)} ${scale.unit ?? ""}` : "حدد مؤشراً لتفعيل التدرج"}</Badge></div><div className="mt-4 flex flex-wrap items-center gap-2">{scale.colors.map((color, index) => <span key={color} className="flex items-center gap-1.5 text-[11px] text-slate-500"><i className="h-4 w-7 rounded-md border border-white shadow-sm" style={{ backgroundColor: color }} />{index === 0 ? "أدنى" : index === scale.colors.length - 1 ? "أعلى" : ""}</span>)}<span className="mr-2 flex items-center gap-1.5 text-[11px] text-slate-500"><i className="h-4 w-7 rounded-md border border-white shadow-sm" style={{ backgroundColor: "#94a3b8" }} />لا قياسات معتمدة</span></div></section>; }
function CityRankingBoard({ rankings, onSelect }: { rankings: { id: string; label: string; description: string; indicator: { name: string } | null; unit: string | null; items: { cityId: number; cityName: string; value: number; year: number }[] }[]; onSelect: (id: number) => void }) { return <section className="rounded-2xl border border-[#dce8e4] bg-white p-5 shadow-sm"><div className="flex flex-col gap-2 md:flex-row md:items-end md:justify-between"><div><h2 className="flex items-center gap-2 font-bold text-[#153c39]"><Trophy className="h-5 w-5 text-[#b98238]" />ترتيب المدن السياحي</h2><p className="mt-1 text-xs leading-6 text-slate-500">كل بطاقة تقارن المدن داخل مؤشر واحد فقط وبحسب أحدث قياس معتمد، لذلك لا تختلط الخدمات أو السياح أو الاستثمار في درجة موحدة.</p></div><Badge variant="outline" className="w-fit border-[#b8d6ce] text-[#0f766e]">{rankings.filter((item) => item.indicator).length} فئات مرتبطة بمؤشرات منشورة</Badge></div><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{rankings.map((ranking) => <article key={ranking.id} className="min-h-44 rounded-xl border border-[#e1ece8] bg-[#fbfdfc] p-4"><div className="flex items-start justify-between gap-2"><div><h3 className="font-bold text-[#173f3c]">{ranking.label}</h3><p className="mt-1 text-[11px] leading-5 text-slate-500">{ranking.indicator?.name ?? ranking.description}</p></div><Badge variant="outline" className="shrink-0 border-[#d5e6e0] text-[10px] text-[#0f766e]">{ranking.indicator ? "مؤشر منشور" : "غير متاح"}</Badge></div>{!ranking.indicator ? <p className="mt-5 rounded-lg border border-dashed border-[#d8e5e1] bg-white p-3 text-xs leading-6 text-slate-500">لا يوجد حالياً مؤشر مكاني منشور لهذه الفئة، لذا لا يظهر ترتيب تقديري.</p> : ranking.items.length === 0 ? <p className="mt-5 rounded-lg border border-dashed border-amber-200 bg-amber-50 p-3 text-xs leading-6 text-amber-900">لا توجد قياسات مدنية معتمدة لهذا المؤشر بعد.</p> : <ol className="mt-4 space-y-2">{ranking.items.slice(0, 3).map((item, index) => <li key={item.cityId}><button onClick={() => onSelect(item.cityId)} className="flex w-full items-center justify-between rounded-lg bg-white px-2.5 py-2 text-right transition hover:bg-[#edf7f3]"><span className="flex items-center gap-2"><b className="grid h-5 w-5 place-items-center rounded-full bg-[#e4f2ed] text-[10px] text-[#0f766e]">{index + 1}</b><span className="text-xs font-semibold text-[#173f3c]">{item.cityName}</span></span><span className="text-[11px] font-bold text-[#0f766e]">{numberFormat.format(item.value)} {ranking.unit}</span></button></li>)}</ol>}</article>)}</div></section>; }
function CityHoverGuide({ cities, summaries, onSelect }: { cities: { id: number; name: string; code: string }[]; summaries: Map<number, LocationQuickStat>; onSelect: (id: number) => void }) { return <section className="rounded-2xl border border-[#dce8e4] bg-white p-5 shadow-sm"><div className="flex items-end justify-between"><div><h2 className="font-bold text-[#153c39]">إحصاءات سريعة للمدن</h2><p className="mt-1 text-xs text-slate-500">مرر فوق البطاقة لعرض أحدث قياس، ثم انقر لفتح التفاصيل.</p></div><Badge variant="outline" className="border-[#b8d6ce] text-[#0f766e]">بيانات معتمدة فقط</Badge></div><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{cities.map((city) => { const stat = summaries.get(city.id) ?? emptyQuickStat(); return <button key={city.id} onClick={() => onSelect(city.id)} className="group relative overflow-visible rounded-xl border border-[#dce8e4] bg-[#fbfdfc] p-3 text-right transition hover:-translate-y-0.5 hover:border-[#92c8bb] hover:shadow-md"><div className="flex items-start justify-between gap-2"><div><p className="font-semibold text-[#173f3c]">{city.name}</p><p className="mt-1 text-[11px] text-slate-500">{city.code}</p></div><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${stat.count ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700"}`}>{stat.count ? `${stat.count} سجل` : "لا سجلات"}</span></div><div className="pointer-events-none absolute inset-x-3 bottom-[calc(100%+8px)] z-30 rounded-xl bg-[#173f3c] px-3 py-2.5 text-xs leading-6 text-white opacity-0 shadow-xl transition duration-200 group-hover:opacity-100"><strong>{stat.count ? `أحدث قياس: ${numberFormat.format(stat.latestValue ?? 0)} ${stat.unit ?? ""}` : "لا توجد قياسات معتمدة"}</strong><br />{stat.count ? `${stat.indicatorName ?? "مؤشر مكاني"} · ${stat.latestYear}` : "أدخل قياساً موثقاً ليظهر هنا."}</div><p className="mt-3 text-xs text-[#0f766e]">{stat.count ? `${stat.count} قياساً معتمداً` : "لا توجد قياسات مكانية معتمدة بعد"}</p></button>; })}</div></section>; }
function CityExportSummary({ cities, rankings, scale, selectedYear, selectedIndicator, onExport, isExporting }: { cities: { id: number; name: string }[]; rankings: { label: string; indicator: { name: string } | null; items: { cityId: number; cityName: string; value: number; year: number }[]; unit: string | null }[]; scale: ReturnType<typeof buildSpatialColorScale>; selectedYear: string; selectedIndicator: string; onExport: (format: "png" | "pdf") => void; isExporting: "png" | "pdf" | null }) { return <section className="rounded-2xl border border-[#cfe3dc] bg-[#f7fbf9] p-5 shadow-sm"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><h2 className="font-bold text-[#153c39]">ملخص المدن القابل للتصدير</h2><p className="mt-1 text-xs leading-6 text-slate-500">يصدر المدن الظاهرة وحالة القياسات المعتمدة ومقياس اللون وترتيب الفئات المتاحة فقط.</p></div><div className="flex gap-2"><Button variant="outline" className="border-[#b8d6ce] text-[#0f766e]" disabled={isExporting !== null} onClick={() => onExport("png")}><ImageDown className="ml-2 h-4 w-4" />{isExporting === "png" ? "جارٍ إنشاء الصورة" : "صورة PNG"}</Button><Button className="bg-[#0f766e] hover:bg-[#0b5f5a]" disabled={isExporting !== null} onClick={() => onExport("pdf")}><FileDown className="ml-2 h-4 w-4" />{isExporting === "pdf" ? "جارٍ إنشاء PDF" : "تصدير PDF"}</Button></div></div><div className="mt-4 grid gap-3 md:grid-cols-3"><ExportTile label="المدن في العرض" value={numberFormat.format(cities.length)} /><ExportTile label="نطاق السنة" value={selectedYear === all ? "كل السنوات" : selectedYear} /><ExportTile label="التدرج اللوني" value={selectedIndicator === all ? "غير مفعل" : scale.min === null ? "لا قياسات معتمدة" : `${numberFormat.format(scale.min)}–${numberFormat.format(scale.max ?? 0)} ${scale.unit ?? ""}`} /></div><div className="mt-4 grid gap-2 md:grid-cols-2">{rankings.filter((item) => item.indicator).map((item) => <div key={item.label} className="rounded-xl border border-[#dce8e4] bg-white px-3 py-2 text-xs"><span className="font-semibold text-[#173f3c]">{item.label}</span><span className="mr-2 text-slate-500">{item.items[0] ? `${item.items[0].cityName}: ${numberFormat.format(item.items[0].value)} ${item.unit}` : "لا قياسات معتمدة"}</span></div>)}</div></section>; }
function CityComparison({ cities, primary, secondary, onPrimary, onSecondary, selectedYear, selectedIndicator, primaryRow, secondaryRow, difference }: { cities: { id: number; name: string }[]; primary: string; secondary: string; onPrimary: (value: string) => void; onSecondary: (value: string) => void; selectedYear: string; selectedIndicator: string; primaryRow: { areaName: string; value: number; unit: string } | undefined; secondaryRow: { areaName: string; value: number; unit: string } | undefined; difference: number | null }) { return <article className="rounded-2xl border border-[#cfe3dc] bg-[#f7fbf9] p-5 shadow-sm"><h2 className="font-bold text-[#153c39]">مقارنة مدينتين</h2><p className="mt-1 text-xs text-slate-500">تستخدم السنة والمؤشر المحددين وتعرض قياسات معتمدة فقط.</p><div className="mt-5 grid gap-3 sm:grid-cols-2"><Select value={primary} onValueChange={onPrimary}><SelectTrigger><SelectValue placeholder="المدينة الأولى" /></SelectTrigger><SelectContent><SelectItem value={all}>اختر المدينة الأولى</SelectItem>{cities.map((city) => <SelectItem key={city.id} value={String(city.id)}>{city.name}</SelectItem>)}</SelectContent></Select><Select value={secondary} onValueChange={onSecondary}><SelectTrigger><SelectValue placeholder="المدينة الثانية" /></SelectTrigger><SelectContent><SelectItem value={all}>اختر المدينة الثانية</SelectItem>{cities.filter((city) => String(city.id) !== primary).map((city) => <SelectItem key={city.id} value={String(city.id)}>{city.name}</SelectItem>)}</SelectContent></Select></div>{selectedYear === all || selectedIndicator === all ? <p className="mt-4 rounded-xl border border-amber-200 bg-amber-50 px-3 py-2 text-xs leading-6 text-amber-900">حدّد سنةً ومؤشراً أولاً لإجراء مقارنة قابلة للقراءة.</p> : primary === all || secondary === all ? <p className="mt-4 text-xs text-slate-500">اختر مدينتين لإظهار المقارنة.</p> : primaryRow && secondaryRow ? <div className="mt-4 grid gap-2 sm:grid-cols-3"><ComparisonValue label={primaryRow.areaName} value={`${numberFormat.format(primaryRow.value)} ${primaryRow.unit}`} /><ComparisonValue label="الفرق" value={`${numberFormat.format(Math.abs(difference ?? 0))} ${primaryRow.unit}`} highlight /><ComparisonValue label={secondaryRow.areaName} value={`${numberFormat.format(secondaryRow.value)} ${secondaryRow.unit}`} /></div> : <p className="mt-4 rounded-xl border border-dashed border-[#bedad1] bg-white px-3 py-2 text-xs leading-6 text-slate-600">لا تتوافر قياسات معتمدة مطابقة للمدينتين في النطاق المحدد.</p>}</article>; }
function CityObservationsTable({ observations }: { observations: { id: number; areaName: string; indicatorName: string; year: number; value: number; unit: string; source: string | null }[] }) { return <article className="overflow-hidden rounded-2xl border border-[#dce8e4] bg-white shadow-sm"><div className="flex items-center justify-between border-b border-[#e5eeeb] px-5 py-4"><div><h2 className="font-bold text-[#153c39]">القياسات المدنية المعتمدة</h2><p className="mt-1 text-xs text-slate-500">تُعرض القياسات السنوية المعتمدة المرتبطة بمدينة فقط.</p></div><Badge variant="outline" className="border-[#b8d6ce] text-[#0f766e]">{numberFormat.format(observations.length)} سجل</Badge></div>{observations.length === 0 ? <div className="p-9 text-center"><MapPinned className="mx-auto h-9 w-9 text-[#91b7ad]" /><p className="mt-3 font-semibold text-[#173f3c]">سجل المدن جاهز لاستقبال البيانات المعتمدة</p><p className="mx-auto mt-2 max-w-xl text-sm leading-7 text-slate-500">تظهر القيم بعد إسنادها إلى مدينة من مصدر رسمي ومرورها بمسار المراجعة والاعتماد.</p></div> : <div className="overflow-auto"><table className="w-full min-w-[640px] text-right text-sm"><thead className="bg-[#f6faf8] text-xs text-slate-500"><tr><th className="px-5 py-3">المدينة</th><th className="px-5 py-3">المؤشر</th><th className="px-5 py-3">السنة</th><th className="px-5 py-3">القيمة</th><th className="px-5 py-3">المصدر</th></tr></thead><tbody>{observations.map((row) => <tr key={row.id} className="border-t border-[#edf2f0]"><td className="px-5 py-3 font-semibold text-[#173f3c]">{row.areaName}</td><td className="px-5 py-3 text-slate-600">{row.indicatorName}</td><td className="px-5 py-3 text-slate-600">{row.year}</td><td className="px-5 py-3 font-bold text-[#0f766e]">{numberFormat.format(row.value)} {row.unit}</td><td className="max-w-64 truncate px-5 py-3 text-xs text-slate-500">{row.source ?? "—"}</td></tr>)}</tbody></table></div>}</article>; }
function ExportTile({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-[#dce8e4] bg-white px-4 py-3"><p className="text-[11px] text-slate-500">{label}</p><p className="mt-1 font-bold text-[#173f3c]">{value}</p></div>; }
function ComparisonValue({ label, value, highlight = false }: { label: string; value: string; highlight?: boolean }) { return <div className={`rounded-xl p-3 text-center ${highlight ? "bg-[#0f766e] text-white" : "border border-[#dce8e4] bg-white text-[#173f3c]"}`}><p className={`text-[11px] ${highlight ? "text-teal-100" : "text-slate-500"}`}>{label}</p><p className="mt-1 text-sm font-bold">{value}</p></div>; }
function emptyQuickStat(): LocationQuickStat { return { count: 0, latestYear: null, latestValue: null, unit: null, indicatorName: null }; }
function mapQuickStatHtml(cityName: string, stat: LocationQuickStat) { return `<div dir="rtl" style="font-family:Arial;padding:6px 4px;min-width:190px"><strong style="font-size:14px">${cityName}</strong><hr style="border:0;border-top:1px solid #e2e8f0;margin:7px 0"/><small>قياسات معتمدة: <b>${stat.count}</b></small><br/>${stat.latestYear ? `<small>أحدث قيمة: <b>${numberFormat.format(stat.latestValue ?? 0)} ${stat.unit ?? ""}</b> (${stat.latestYear})</small><br/><small>${stat.indicatorName ?? ""}</small>` : "<small>لا توجد قياسات معتمدة بعد</small>"}</div>`; }
