import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { BarChart3, CheckCircle2, Clock3, MessageSquareReply, MessagesSquare, Paperclip, ThumbsDown, ThumbsUp } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";

const stateLabels = { open: "جديدة", in_progress: "قيد المتابعة", resolved: "تم الحل", closed: "أغلقت" } as const;
const categoryLabels = { question: "استفسار", issue: "مشكلة", suggestion: "اقتراح" } as const;

export default function SupportAdmin() {
  const utils = trpc.useUtils();
  const inbox = trpc.support.inbox.useQuery();
  const updateStatus = trpc.support.updateStatus.useMutation({ onSuccess: () => { utils.support.inbox.invalidate(); toast.success("تم تحديث حالة الطلب."); }, onError: (error) => toast.error(error.message) });
  const reply = trpc.support.reply.useMutation({ onSuccess: () => { utils.support.inbox.invalidate(); toast.success("تم إرسال رد الإدارة وتحديث الطلب للمتابعة."); }, onError: (error) => toast.error(error.message) });
  const stats = useMemo(() => {
    const requests = inbox.data?.requests ?? [];
    const ratings = inbox.data?.ratingSummary ?? [];
    const helpful = ratings.reduce((sum, row) => sum + row.helpful, 0);
    const notHelpful = ratings.reduce((sum, row) => sum + row.notHelpful, 0);
    return { total: requests.length, open: requests.filter((item) => item.status === "open").length, progress: requests.filter((item) => item.status === "in_progress").length, helpful, notHelpful };
  }, [inbox.data]);
  if (inbox.isLoading) return <div className="rounded-2xl bg-white p-8 text-center text-slate-500">جارٍ تحميل لوحة الدعم…</div>;
  return <div className="space-y-6"><section className="rounded-[2rem] bg-[linear-gradient(135deg,#123f3c,#0f766e)] p-6 text-white shadow-[0_20px_55px_rgba(12,76,73,.18)] md:p-8"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-white/15"><MessagesSquare className="h-6 w-6" /></span><div><p className="text-xs font-bold tracking-[.14em] text-amber-200">إدارة الدعم</p><h1 className="mt-1 text-2xl font-bold">لوحة رسائل المستخدمين وتقييمات الدليل</h1><p className="mt-3 text-sm leading-7 text-teal-50/90">إدارة مركزية للطلبات والردود والمرفقات، مع مؤشرات تحسين محتوى المساعدة.</p></div></div></section><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Metric icon={MessagesSquare} label="إجمالي الطلبات" value={stats.total} tone="teal" /><Metric icon={Clock3} label="طلبات جديدة" value={stats.open} tone="amber" /><Metric icon={MessageSquareReply} label="قيد المتابعة" value={stats.progress} tone="blue" /><Metric icon={ThumbsUp} label="تقييمات مفيدة" value={stats.helpful} tone="teal" /><Metric icon={ThumbsDown} label="تقييمات غير مفيدة" value={stats.notHelpful} tone="rose" /></section><section className="rounded-2xl border border-[#dce8e4] bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#e9f4f1] text-[#0f766e]"><BarChart3 className="h-5 w-5" /></span><div><h2 className="font-bold text-[#173f3d]">أداء محتوى المساعدة</h2><p className="mt-1 text-sm text-slate-500">تجمعات مجهولة الهوية؛ تستخدم لتحديد الأقسام التي تحتاج إلى توضيح.</p></div></div><div className="mt-4 grid gap-2 md:grid-cols-2 xl:grid-cols-3">{inbox.data?.ratingSummary.length ? inbox.data.ratingSummary.map((row) => <div key={row.sectionId} className="rounded-xl border border-[#e3ece9] bg-[#fbfdfc] p-3"><p className="text-sm font-semibold text-[#173f3d]">{row.sectionId}</p><p className="mt-2 text-xs text-slate-600">مفيد: {row.helpful} · غير مفيد: {row.notHelpful}</p></div>) : <p className="text-sm text-slate-500">لا توجد تقييمات بعد.</p>}</div></section><section className="space-y-4">{inbox.data?.requests.length ? inbox.data.requests.map((request) => <AdminRequestCard key={request.id} request={request} pending={updateStatus.isPending || reply.isPending} onStatus={(status) => updateStatus.mutate({ id: request.id, status })} onReply={(message) => reply.mutate({ supportRequestId: request.id, message })} />) : <div className="rounded-2xl border border-dashed border-[#c8ded7] bg-white p-10 text-center text-slate-500">لا توجد طلبات دعم مسجلة حتى الآن.</div>}</section></div>;
}

function Metric({ icon: Icon, label, value, tone }: { icon: typeof MessagesSquare; label: string; value: number; tone: "teal" | "amber" | "blue" | "rose" }) { const tones = { teal: "bg-teal-50 text-teal-700", amber: "bg-amber-50 text-amber-700", blue: "bg-sky-50 text-sky-700", rose: "bg-rose-50 text-rose-700" }; return <article className="rounded-2xl border border-[#dce8e4] bg-white p-4 shadow-sm"><span className={`grid h-9 w-9 place-items-center rounded-xl ${tones[tone]}`}><Icon className="h-4 w-4" /></span><p className="mt-3 text-xs text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold text-[#173f3d]">{value}</p></article>; }
function AdminRequestCard({ request, pending, onStatus, onReply }: { request: any; pending: boolean; onStatus: (status: keyof typeof stateLabels) => void; onReply: (message: string) => void }) { const [message, setMessage] = useState(""); return <article className="rounded-2xl border border-[#dce8e4] bg-white p-5 shadow-sm"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h2 className="font-bold text-[#173f3d]">{request.subject}</h2><Badge variant="outline" className="border-[#b9d7cf] text-[#0f766e]">{categoryLabels[request.category as keyof typeof categoryLabels]}</Badge><Badge className="border-0 bg-slate-100 text-slate-700">{stateLabels[request.status as keyof typeof stateLabels]}</Badge></div><p className="mt-3 whitespace-pre-wrap text-sm leading-7 text-slate-600">{request.message}</p><p className="mt-2 text-xs text-slate-500">{request.submitterName ?? "مستخدم المنصة"}{request.submitterEmail ? ` — ${request.submitterEmail}` : ""} · {new Date(request.createdAt).toLocaleString("ar-LY")}</p></div><Select value={request.status} onValueChange={onStatus} disabled={pending}><SelectTrigger className="w-full bg-white lg:w-40"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="open">جديدة</SelectItem><SelectItem value="in_progress">قيد المتابعة</SelectItem><SelectItem value="resolved">تم الحل</SelectItem><SelectItem value="closed">أغلقت</SelectItem></SelectContent></Select></div>{request.attachments?.length ? <div className="mt-4 flex flex-wrap gap-2 border-t border-[#edf2f0] pt-4">{request.attachments.map((attachment: any) => <a key={attachment.id} className="inline-flex items-center gap-1 rounded-lg border border-[#cfe3dc] bg-[#f7faf9] px-3 py-1.5 text-xs text-[#0f766e] hover:bg-[#e9f4f1]" href={attachment.storageUrl} target="_blank" rel="noreferrer"><Paperclip className="h-3.5 w-3.5" />{attachment.fileName}</a>)}</div> : null}{request.replies?.length ? <div className="mt-4 space-y-2 border-t border-[#edf2f0] pt-4">{request.replies.map((reply: any) => <div key={reply.id} className="rounded-xl bg-[#eaf5f1] p-3 text-sm leading-6 text-[#173f3d]"><strong className="text-xs">{reply.authorName ?? "الإدارة"}</strong><p className="mt-1 whitespace-pre-wrap">{reply.message}</p></div>)}</div> : null}<div className="mt-4 grid gap-2 border-t border-[#edf2f0] pt-4 sm:grid-cols-[1fr_auto]"><Textarea value={message} onChange={(event) => setMessage(event.target.value)} className="min-h-20" maxLength={5000} placeholder="اكتب رد الإدارة للمستخدم…" /><Button disabled={pending || message.trim().length < 3} className="bg-[#0f766e] hover:bg-[#0a5f58]" onClick={() => { onReply(message.trim()); setMessage(""); }}><CheckCircle2 className="ml-1.5 h-4 w-4" />إرسال الرد</Button></div></article>; }
