export const ENV = {
  authProvider: process.env.AUTH_PROVIDER ?? "manus",
  appId: process.env.AUTH_CLIENT_ID ?? process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  authClientSecret: process.env.AUTH_CLIENT_SECRET ?? "",
  oidcIssuerUrl: process.env.OIDC_ISSUER_URL ?? "",
  oidcTokenUrl: process.env.OIDC_TOKEN_URL ?? "",
  oidcJwksUrl: process.env.OIDC_JWKS_URL ?? "",
  oidcUserInfoUrl: process.env.OIDC_USERINFO_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  deploymentEnvironment: process.env.TOURISM_DEPLOYMENT_ENV ?? "development",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  storagePublicBaseUrl: process.env.PUBLIC_STORAGE_BASE_URL ?? "/manus-storage",
  readinessTimeoutMs: Number(process.env.READINESS_TIMEOUT_MS ?? 3_000),
};
