export const historicalOfficialPublisher = {
  name: "مركز المعلومات والتوثيق السياحي",
  verificationUrl: "https://tidc.com.ly/releases.php?page=1",
  verificationLabel: "صفحة الإصدارات الرسمية",
} as const;

export const historicalSourceRegistry = [
  { fileName: "احصائية الليالي السياحية بمرافق الإيواء (1993).xlsx", coverage: "1993", status: "أرشيف تفصيلي", detail: "ليالٍ شهرية بحسب المرفق والمدينة؛ لا تمثل إجمالياً وطنياً قبل مراجعة اكتمال المرافق والأشهر.", approvalStatus: "غير مدخل كسلسلة سنوية", matchedCodes: "—", verificationUrl: historicalOfficialPublisher.verificationUrl },
  { fileName: "عدد السياح 1994.docx", coverage: "1994–1998", status: "مستورد ومعتمد", detail: "إجماليات الزوار والسياح على المستوى الوطني.", approvalStatus: "معتمد", matchedCodes: "HIST-VISITORS-TOTAL، HIST-TOURISTS-OVERNIGHT", verificationUrl: historicalOfficialPublisher.verificationUrl },
  { fileName: "زوار 1997-2000.docx", coverage: "1997–2000", status: "مستورد جزئياً", detail: "إجمالي الزوار وتفصيلهم بحسب الجنسية والمنطقة؛ استُخدمت الإجماليات الوطنية غير المكررة فقط.", approvalStatus: "معتمد للقياسات غير المكررة", matchedCodes: "HIST-VISITORS-TOTAL", verificationUrl: historicalOfficialPublisher.verificationUrl },
  { fileName: "التقرير الإحصائي 2004-2005-2006م.xls", coverage: "2004–2006", status: "مصدر مرجعي معتمد", detail: "يؤيد سلاسل الوافدين والليالي والإيواء ضمن التقارير الوطنية.", approvalStatus: "معتمد", matchedCodes: "HIST-ARRIVALS-TOTAL، HIST-HOTELS، HIST-ROOMS، HIST-BEDS، HIST-HOTEL-GUESTS، HIST-OVERNIGHT-STAYS", verificationUrl: historicalOfficialPublisher.verificationUrl },
  { fileName: "التقرير الإحصائي لسنة 2007م.xls", coverage: "2007", status: "مصدر مرجعي معتمد", detail: "مؤشرات السياحة والإيواء لعام 2007.", approvalStatus: "معتمد", matchedCodes: "HIST-ARRIVALS-TOTAL، HIST-HOTELS، HIST-ROOMS، HIST-BEDS، HIST-HOTEL-GUESTS، HIST-OVERNIGHT-STAYS", verificationUrl: historicalOfficialPublisher.verificationUrl },
  { fileName: "التقرير الإحصائي لسنة 2008م.xls", coverage: "2008", status: "مصدر مرجعي معتمد", detail: "مؤشرات السياحة والإيواء لعام 2008.", approvalStatus: "معتمد", matchedCodes: "HIST-ARRIVALS-TOTAL، HIST-HOTELS، HIST-ROOMS، HIST-BEDS، HIST-HOTEL-GUESTS، HIST-OVERNIGHT-STAYS", verificationUrl: historicalOfficialPublisher.verificationUrl },
  { fileName: "التقرير الإحصائي لسنة 2009م.xls", coverage: "2009", status: "مصدر مرجعي معتمد", detail: "مؤشرات السياحة والإيواء لعام 2009.", approvalStatus: "معتمد", matchedCodes: "HIST-ARRIVALS-TOTAL، HIST-HOTELS، HIST-ROOMS، HIST-BEDS، HIST-HOTEL-GUESTS، HIST-OVERNIGHT-STAYS", verificationUrl: historicalOfficialPublisher.verificationUrl },
  { fileName: "التقرير الإحصائي لسنة 2010م.xls", coverage: "2010", status: "مصدر مرجعي معتمد", detail: "مؤشرات السياحة والإيواء لعام 2010.", approvalStatus: "معتمد", matchedCodes: "HIST-ARRIVALS-TOTAL، HIST-HOTELS، HIST-ROOMS، HIST-BEDS، HIST-HOTEL-GUESTS، HIST-OVERNIGHT-STAYS", verificationUrl: historicalOfficialPublisher.verificationUrl },
  { fileName: "التقرير الإحصائي للسنوات 2014-2015-2016م.xls", coverage: "2000–2016", status: "مستورد ومعتمد", detail: "الجداول الوطنية الموحدة للفنادق والغرف والأسرة والليالي والعمالة والخدمات.", approvalStatus: "معتمد", matchedCodes: "HIST-ARRIVALS-TOTAL، HIST-HOTELS، HIST-ROOMS، HIST-BEDS، HIST-HOTEL-GUESTS، HIST-OVERNIGHT-STAYS، HIST-ACCOMMODATION-EMPLOYMENT، HIST-TOURISM-COMPANIES، HIST-TOURISM-COOPERATIVES، HIST-TOURISM-OFFICES", verificationUrl: historicalOfficialPublisher.verificationUrl },
  { fileName: "التقرير الإحصائي للأقاليم الأربعة 2014-2015-2016م.xls", coverage: "2013–2016", status: "أرشيف مكاني", detail: "تفصيل إقليمي ومديني يحتاج نموذجاً مكانياً منفصلاً قبل إدراجه كمؤشر وطني.", approvalStatus: "غير مدخل كمؤشر وطني", matchedCodes: "—", verificationUrl: historicalOfficialPublisher.verificationUrl },
  { fileName: "التقرير الإحصائي للسنوات 2017-2018م.xls", coverage: "2017–2018", status: "يتطلب مراجعة", detail: "تحتاج السنة المرجعية لبعض الجداول إلى تثبيت قبل تحويلها إلى قياسات سنوية.", approvalStatus: "لم يعتمد", matchedCodes: "—", verificationUrl: historicalOfficialPublisher.verificationUrl },
  { fileName: "تجميع بيانات من 2021 إلى 2025.xlsx", coverage: "2021–2025", status: "مستورد جزئياً", detail: "استوردت قيم 2021–2024 الكاملة؛ بيانات 2025 الواردة في الملف تصف النصف الأول من السنة.", approvalStatus: "معتمد للأعوام 2021–2024 فقط", matchedCodes: "HIST-ACCOMMODATION-FACILITIES", verificationUrl: historicalOfficialPublisher.verificationUrl },
  { fileName: "إحصائيات ومؤشرات سياحية لسنة 2023.pdf", coverage: "2023", status: "مستورد ومعتمد", detail: "ثمانية قياسات سنوية واضحة، مع أرقام الصفحات المسجلة في ملاحظات كل قياس.", approvalStatus: "معتمد", matchedCodes: "HIST-HOTELS، HIST-ROOMS، HIST-BEDS، HIST-TOURIST-VILLAGES، HIST-TOURISM-COMPANIES، HIST-TOURISM-OFFICES، HIST-TOURISM-RESTAURANTS-CAFES، HIST-TOURISM-GUIDES", verificationUrl: historicalOfficialPublisher.verificationUrl },
  { fileName: "التقرير الإحصائي للقطاع السياحي لسنة 2025.pdf", coverage: "2025", status: "مستورد ومعتمد", detail: "عشرة قياسات سنوية واضحة، مع أرقام الصفحات المسجلة في ملاحظات كل قياس.", approvalStatus: "معتمد", matchedCodes: "HIST-ACCOMMODATION-GUESTS، HIST-INTERNATIONAL-TOURISTS، HIST-ACCOMMODATION-FACILITIES، HIST-HOTELS، HIST-HOTEL-APARTMENTS، HIST-ROOMS، HIST-BEDS، HIST-TOURIST-VILLAGES، HIST-TOURISM-BUSINESSES-COMBINED، HIST-TOURISM-RESTAURANTS-CAFES", verificationUrl: historicalOfficialPublisher.verificationUrl },
  { fileName: "مشروع التنبؤ 2035.xlsx", coverage: "2025–2035", status: "تنبؤ منفصل", detail: "لا يعد مصدراً تاريخياً ولا يدمج مع القياسات الفعلية.", approvalStatus: "غير مدخل", matchedCodes: "—", verificationUrl: historicalOfficialPublisher.verificationUrl },
] as const;
