import { Badge } from "@/components/ui/badge";
import { Trophy } from "lucide-react";

export type CityRankingPanelItem = {
  id: string;
  label: string;
  description: string;
  indicator: { id: number; name: string } | null;
  unit: string | null;
  items: { cityId: number; cityName: string; value: number; year: number }[];
};

export function CityRankingPanels({ rankings, highlightedCity, onSelect }: { rankings: CityRankingPanelItem[]; highlightedCity: number | null; onSelect: (cityId: number, indicatorId: number | null, categoryId: string) => void }) {
  return <section className="rounded-2xl border border-[#dce8e4] bg-white p-5 shadow-sm"><div className="flex flex-col gap-2 md:flex-row md:items-end md:justify-between"><div><h2 className="flex items-center gap-2 font-bold text-[#153c39]"><Trophy className="h-5 w-5 text-[#b98238]" />ترتيب المدن السياحي</h2><p className="mt-1 text-xs leading-6 text-slate-500">اضغط فئة لربطها بالخريطة، ثم اختر مدينة من القائمة لإبرازها. لا تقارن البطاقات إلا مدناً داخل المؤشر نفسه.</p></div><Badge variant="outline" className="w-fit border-[#b8d6ce] text-[#0f766e]">{rankings.filter((item) => item.indicator).length} فئات منشورة</Badge></div><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{rankings.map((ranking) => <article key={ranking.id} className="min-h-44 rounded-xl border border-[#e1ece8] bg-[#fbfdfc] p-4"><button disabled={!ranking.indicator} onClick={() => onSelect(ranking.items[0]?.cityId ?? -1, ranking.indicator?.id ?? null, ranking.id)} className="w-full text-right disabled:cursor-default"><div className="flex items-start justify-between gap-2"><div><h3 className="font-bold text-[#173f3c]">{ranking.label}</h3><p className="mt-1 text-[11px] leading-5 text-slate-500">{ranking.indicator?.name ?? ranking.description}</p></div><Badge variant="outline" className="shrink-0 border-[#d5e6e0] text-[10px] text-[#0f766e]">{ranking.indicator ? "اربط بالخريطة" : "غير متاح"}</Badge></div></button>{!ranking.indicator ? <p className="mt-5 rounded-lg border border-dashed border-[#d8e5e1] bg-white p-3 text-xs leading-6 text-slate-500">لا يوجد حالياً مؤشر منشور لهذه الفئة.</p> : ranking.items.length === 0 ? <p className="mt-5 rounded-lg border border-dashed border-amber-200 bg-amber-50 p-3 text-xs leading-6 text-amber-900">المؤشر مفعّل، لكنه ينتظر قياسات مدنية معتمدة.</p> : <ol className="mt-4 space-y-2">{ranking.items.slice(0, 3).map((item, index) => <li key={item.cityId}><button onClick={() => onSelect(item.cityId, ranking.indicator?.id ?? null, ranking.id)} className={`flex w-full items-center justify-between rounded-lg px-2.5 py-2 text-right transition ${highlightedCity === item.cityId ? "bg-amber-100 ring-1 ring-amber-400" : "bg-white hover:bg-[#edf7f3]"}`}><span className="flex items-center gap-2"><b className="grid h-5 w-5 place-items-center rounded-full bg-[#e4f2ed] text-[10px] text-[#0f766e]">{index + 1}</b><span className="text-xs font-semibold text-[#173f3c]">{item.cityName}</span></span><span className="text-[11px] font-bold text-[#0f766e]">{new Intl.NumberFormat("ar-LY").format(item.value)} {ranking.unit}</span></button></li>)}</ol>}</article>)}</div></section>;
}
