import { SupportAdminExportControls } from "@/components/SupportAdminExportControls";
import { buildSupportInsights, type SupportInsightRequest } from "@/lib/supportInsights";
import { trpc } from "@/lib/trpc";
import { BarChart3, CircleHelp, Repeat2 } from "lucide-react";
import { useMemo } from "react";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

export function SupportInsightsPanel({ requests }: { requests: SupportInsightRequest[] }) {
  const insights = useMemo(() => buildSupportInsights(requests), [requests]);
  const inbox = trpc.support.inbox.useQuery();
  return <section id="support-admin-report" className="rounded-2xl border border-[#dce8e4] bg-white p-5 shadow-sm"><div className="flex flex-col gap-4 xl:flex-row xl:items-start xl:justify-between"><div className="flex items-start gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#e9f4f1] text-[#0f766e]"><BarChart3 className="h-5 w-5" /></span><div><h2 className="font-bold text-[#173f3d]">اتجاهات أسئلة ومشكلات الدعم</h2><p className="mt-1 text-sm text-slate-500">رسوم مشتقة من رسائل الدعم الفعلية، ولا تعرض بيانات أو أمثلة مصطنعة.</p></div></div></div><div className="mt-4"><SupportAdminExportControls requests={requests} ratings={inbox.data?.ratingSummary ?? []} /></div><div className="mt-5 grid gap-5 xl:grid-cols-2"><article className="rounded-xl border border-[#e3ece9] bg-[#fbfdfc] p-4"><h3 className="flex items-center gap-2 text-sm font-bold text-[#173f3d]"><CircleHelp className="h-4 w-4 text-[#0f766e]" />توزيع أنواع الطلبات</h3><div className="mt-3 h-52">{requests.length ? <ResponsiveContainer width="100%" height="100%"><BarChart data={insights.categoryCounts} margin={{ top: 8, right: 8, left: -20, bottom: 4 }}><CartesianGrid vertical={false} stroke="#e4efeb" /><XAxis dataKey="name" tick={{ fontSize: 11, fill: "#58736d" }} /><YAxis allowDecimals={false} tick={{ fontSize: 11, fill: "#58736d" }} /><Tooltip cursor={{ fill: "#eff7f3" }} /><Bar dataKey="count" name="عدد الطلبات" fill="#0f766e" radius={[7, 7, 0, 0]} /></BarChart></ResponsiveContainer> : <EmptyChart label="لا توجد طلبات بعد لعرض توزيعها." />}</div></article><article className="rounded-xl border border-[#e3ece9] bg-[#fbfdfc] p-4"><h3 className="flex items-center gap-2 text-sm font-bold text-[#173f3d]"><Repeat2 className="h-4 w-4 text-[#0f766e]" />الكلمات المتكررة في الرسائل</h3><div className="mt-3 h-52">{insights.commonTerms.length ? <ResponsiveContainer width="100%" height="100%"><BarChart layout="vertical" data={insights.commonTerms} margin={{ top: 4, right: 18, left: 18, bottom: 4 }}><CartesianGrid horizontal={false} stroke="#e4efeb" /><XAxis type="number" allowDecimals={false} tick={{ fontSize: 11, fill: "#58736d" }} /><YAxis dataKey="name" type="category" width={80} tick={{ fontSize: 11, fill: "#58736d" }} /><Tooltip cursor={{ fill: "#eff7f3" }} /><Bar dataKey="count" name="مرات التكرار" fill="#c58a3f" radius={[0, 7, 7, 0]} /></BarChart></ResponsiveContainer> : <EmptyChart label="تظهر الكلمات بعد تكرارها في رسالتين أو أكثر." />}</div></article></div></section>;
}
function EmptyChart({ label }: { label: string }) { return <div className="grid h-full place-items-center rounded-lg border border-dashed border-[#c8ded7] text-center text-sm text-slate-500">{label}</div>; }
